### ISSUE TITLE
Defined processes must be followed.

### ISSUE THREAD

**Issue by sarvesh-0** [sarvesh-0/C-Basics#32]
Dear All,

Even after vigil from all of us (particularly me and contributors), I see the main branch is broken as many of the files are pushed to it without following the due procedure. I am listing some of them here and would discuss the way forward.

          1. Expense.c and Expense.exe file
          2. Example of while loop.
          3. file
          4. if ilse and logical operator

Not only this, there's a confusion around what is the default branch into which all the feature branches should get merged. It's good we are learning from mistakes, but repeating the same one again and again wouldn't work. Looking forward for your suggestions.

Thank You
Sarvesh

**Comment by Anjali-1801** [comment]
Yes sir! Also, I had one concern. I received mails yesterday that the PRs that I was reviewing was merged by someone else. I already had gone through those programs and duly commented that these changes were required, I even explained how those changes could be made and pushed back, but before the changes were made someone merged them. 

I just want to request you to add this point to the guidelines that the PR which is already under review by someone must not be merged by the other person.

**Comment by CrescentSurfing** [comment]
The changes to the repository should be pushed in respective folders created on the repository instead of merging it to the main branch.
